### ISSUE TITLE
Add options modal

### ISSUE THREAD

**Issue by bidah** [calebnance/expo-spotify#2]
Hey there. I was wondering if you would like some help. It's a big interface. I am playing with adding the options (...) modal with blur in my fork. Tell me if you are ok with it or if you are already working on it. If it's fine tell me to send you a PR when done.

**Comment by calebnance** [comment]
hi @bidah would love to see it! open a PR and I will take a look. Thanks!

**Comment by bidah** [comment]
Great! I have a working version now! will clean it up and sent that pull request 👍

**Comment by calebnance** [comment]
Thanks dude!

**Comment by bidah** [comment]
PR for blurry modal sent! Sorry for the delay! :sweat: @calebnance #4
